export const GAME_CRITICAL_IMAGE_ASSET_URLS = [
  "/scene-layers/background_facade.png",
  "/scene-layers/foreground_curb.png",
  "/pole-pack/pole.png",
  "/pole-pack/pole-security-effect.png",
  "/pole-pack/pole-signal-spritesheet.png",
  "/attack/bullet-spritesheet.png",
  "/attack/damage-label/ack-flood.png",
  "/attack/damage-label/dns-amp.png",
  "/attack/damage-label/http-flood.png",
  "/attack/damage-label/ntp-amp.png",
  "/attack/damage-label/syn-flood.png",
  "/attack/damage-label/udp-flood.png",
  "/texture-pack/damage_overlay_1.png",
  "/texture-pack/damage_overlay_2.png",
  "/texture-pack/container_2-2_default_spritesheet.png",
  "/texture-pack/container_3-2_default_spritesheet.png",
  "/texture-pack/neutral_01.png",
  "/texture-pack/neutral_dark.png",
  "/texture-pack/neutral_signal.png",
  "/texture-pack/ddg_core.png",
  "/texture-pack/postgres.png",
  "/texture-pack/nginx.png",
  "/texture-pack/docker-squre.png",
  "/texture-pack/k8s.png",
  "/texture-pack/docker-rect.png",
  "/texture-pack/ddg_shield.png",
  "/texture-pack/audit_module.png",
] as const;

export const GAME_DEFERRED_IMAGE_ASSET_URLS: readonly string[] = [];
